name: Azure Bicep Infrastructure Deployment

inputs:
  customParameters:
    description: "Additional parameter file input  pairs in string format. e.g. 'storagePrefix=mystore storageSKU=Standard_LRS"
    required: false
    default: ''
  AZURE_CREDENTIALS:
    required: true 
  AZURE_SUBSCRIPTION:
    required: true 

runs:
  using: 'composite'
  steps:
      # Log into Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }} 

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ inputs.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.resourceGroupName }}
        template: ./IaC-Demo/infra.bicep
        parameters: ${{ inputs.customParameters }}
        failOnStdErr: false