name: Deploy

on: 
  push:
    branches:
      - main
    paths:
      - 'App-Demo/**'
  workflow_dispatch:

jobs:
  ReuseableMatrixJobForDeployment:
    runs-on: windows-latest
    continue-on-error: false
    strategy:
      max-parallel: 1
      matrix:
        target: [dev, stage, prod]
    environment: ${{ matrix.target }}
    uses: ./.github/workflows/workflow.yml
    with:
      environment: ${{ matrix.target }}

