name: Deploy with Matrix

on: 
  push:
    branches:
      - main
    paths:
      - 'App-Demo/**'
  workflow_dispatch:

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      max-parallel: 1
      matrix:
        target: [Dev, Stage, Prod]
    uses: ./.github/workflows/deploy_workflow.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit