name:  Deployment to Dev

on: 
  push:
    branches:
      - main
    paths:
      - 'App-Demo/**'
  workflow_dispatch:

env:
  resourceGroupName: 'rg-webapp-infras'
  subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
  dotNetVersion: '3.1.x'
  creds: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  job_deploy_infrastructure:
    runs-on: windows-latest
    name: 'Deploy Azure Infrastructure'
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy Bicep File'
        uses: ./.github/actions/deployInfra
        with:
          customParameters: 'votingWebAppName=SergioApp'

  job_deploy_webapi:
    runs-on: windows-latest
    name: 'Deploy Web Api'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/actions/deployApp
        with:
          azureWebAppName: 'web-votingapi-2xf7pjkzgmtkw'
          webAppSourcePath: '.\App-Demo\src\VotingData'

  job_deploy_webapp:
    runs-on: windows-latest
    name: 'Deploy Web App'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/actions/deployApp
        with:
          azureWebAppName: 'webapp-118593132'
          webAppSourcePath: '.\App-Demo\src\VotingWeb'

  job_deploy_function:
    runs-on: windows-latest
    name: 'Deploy Azure Function'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy Function to Azure Web App Plan'
        uses: ./.github/actions/deployApp
        with:
          azureWebAppName: 'func-votecounter-2xf7pjkzgmtkw'
          webAppSourcePath: '.\App-Demo\src\FunctionApp'