name:  Deployment to Dev

on: 
  push:
    branches:
      - main
    paths:
      - 'App-Demo/**'
  workflow_dispatch:

env:
  resourceGroupName: 'AzureDevOpsLab'
  subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION}}
  dotNetVersion:

jobs:
  job_deploy_infrastructure:
    runs-on: windows-latest
    name: 'Deploy Azure Infrastructure'
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy Bicep File'
        uses: ./.github/actions/deployApp
        with:
          resourceGroupName: '${{ env.resourceGroupName }}'
          subscriptionId: '${{ env.subscriptionId }}'
          customParameters: '${{ env.customParameters }}'

  job_deploy_webapi:
    runs-on: windows-latest
    name: 'Deploy Web Api'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/actions/deployApp
        with:
          azureWebAppName: 'web-votingapi-NavarApp-dev'
          webAppPackagePath: './App-Demo/src/VotingData'
          dotNetVersion: '${{ env.dotNetVersion }}'

  job_deploy_webapp:
    runs-on: windows-latest
    name: 'Deploy Web App'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/actions/deployApp
        with:
          azureWebAppName: 'web-NavarApp-dev'
          webAppPackagePath: './App-Demo/src/VotingWeb'
          dotNetVersion: '${{ env.dotNetVersion }}'