name:  'Reusable workflow to deploy'

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  resourceGroupName: 'GitHubTestRG'
  dotNetVersion: '3.1.x'

jobs:
  job_deploy_infrastructure:
    environment: ${{ inputs.environment }}
    uses: ./.github/workflows/deploy_Infra.yml
    with:
      customParameters: 'votingWebAppName=SergioApp env=${{ inputs.environment }}'
    secrets: inherit


  job_deploy_webapi:
    environment: ${{ inputs.environment }}
    needs: 
      - job_deploy_infrastructure
    uses: ./.github/workflows/deploy_App.yml
    with:
      azureWebAppName: 'web-votingapi-SergioApp-${{ inputs.environment }}'
      webAppSourcePath: '.\App-Demo\src\VotingData'
    secrets: inherit

  job_deploy_webapp:
    environment: ${{ inputs.environment }}
    needs: 
      - job_deploy_infrastructure
    uses: ./.github/workflows/deploy_App.yml
    with:
      azureWebAppName: 'web-SergioApp-${{ inputs.environment }}'
      webAppSourcePath: '.\App-Demo\src\VotingWeb'
    secrets: inherit

  job_deploy_function:
    environment: ${{ inputs.environment }}
    needs: 
      - job_deploy_infrastructure
    uses: ./.github/workflows/deploy_App.yml
    with:
      azureWebAppName: 'func-votecounter-SergioApp-${{ inputs.environment }}'
      webAppSourcePath: '.\App-Demo\src\FunctionApp'
    secrets: inherit
