name:  'Reusable workflow to deploy'

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  resourceGroupName: 'GitHubTestRG'
  dotNetVersion: '3.1.x'

jobs:
  job_deploy_infrastructure:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    name: 'Deploy Azure Infrastructure'
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy Bicep File'
        uses: ./.github/actions/deployInfra
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        with:
          customParameters: 'votingWebAppName=SergioApp env=${{ inputs.environment }}'


  job_deploy_webapi:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    name: 'Deploy Web Api'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/actions/deployApp
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          azureWebAppName: 'web-votingapi-SergioApp-${{ inputs.environment }}'
          webAppSourcePath: '.\App-Demo\src\VotingData'



  job_deploy_webapp:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    name: 'Deploy Web App'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/actions/deployApp
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          azureWebAppName: 'web-SergioApp-${{ inputs.environment }}'
          webAppSourcePath: '.\App-Demo\src\VotingWeb'

  job_deploy_function:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    name: 'Deploy Azure Function'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy Function to Azure Web App Plan'
        uses: ./.github/actions/deployApp
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          azureWebAppName: 'func-votecounter-SergioApp-${{ inputs.environment }}'
          webAppSourcePath: '.\App-Demo\src\FunctionApp'
