name:  'Reusable workflow to deploy'

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  resourceGroupName: 'GitHubTestRG'
  dotNetVersion: '3.1.x'

jobs:
  job_deploy_infrastructure:
    environment: ${{ inputs.environment }}
    name: 'Deploy Azure Infrastructure'
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy Bicep File'
        uses: ./.github/workflows/deploy_Infra.yml
        with:
          customParameters: 'votingWebAppName=SergioApp env=${{ inputs.environment }}'
        secrets: inherit


  job_deploy_webapi:
    environment: ${{ inputs.environment }}
    name: 'Deploy Web Api'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/workflows/deploy_App.yml
        with:
          azureWebAppName: 'web-votingapi-SergioApp-${{ inputs.environment }}'
          webAppSourcePath: '.\App-Demo\src\VotingData'
        secrets: inherit



  job_deploy_webapp:
    environment: ${{ inputs.environment }}
    name: 'Deploy Web App'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy to Azure Web App'
        uses: ./.github/workflows/deploy_App.yml
        with:
          azureWebAppName: 'web-SergioApp-${{ inputs.environment }}'
          webAppSourcePath: '.\App-Demo\src\VotingWeb'
        secrets: inherit

  job_deploy_function:
    environment: ${{ inputs.environment }}
    name: 'Deploy Azure Function'
    needs: 
      - job_deploy_infrastructure
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Deploy Function to Azure Web App Plan'
        uses: ./.github/workflows/deploy_App.yml
        with:
          azureWebAppName: 'func-votecounter-SergioApp-${{ inputs.environment }}'
          webAppSourcePath: '.\App-Demo\src\FunctionApp'
        secrets: inherit
